package com.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RegisterOfFarmers service. Represents a row in the &quot;Test_RegisterOfFarmers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.RegisterOfFarmersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.RegisterOfFarmersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegisterOfFarmers
 * @see com.test.model.impl.RegisterOfFarmersImpl
 * @see com.test.model.impl.RegisterOfFarmersModelImpl
 * @generated
 */
public interface RegisterOfFarmersModel extends BaseModel<RegisterOfFarmers> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a register of farmers model instance should use the {@link RegisterOfFarmers} interface instead.
     */

    /**
     * Returns the primary key of this register of farmers.
     *
     * @return the primary key of this register of farmers
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this register of farmers.
     *
     * @param primaryKey the primary key of this register of farmers
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the register of farmers ID of this register of farmers.
     *
     * @return the register of farmers ID of this register of farmers
     */
    public long getRegisterOfFarmersId();

    /**
     * Sets the register of farmers ID of this register of farmers.
     *
     * @param registerOfFarmersId the register of farmers ID of this register of farmers
     */
    public void setRegisterOfFarmersId(long registerOfFarmersId);

    /**
     * Returns the organization name of this register of farmers.
     *
     * @return the organization name of this register of farmers
     */
    @AutoEscape
    public String getOrganizationName();

    /**
     * Sets the organization name of this register of farmers.
     *
     * @param organizationName the organization name of this register of farmers
     */
    public void setOrganizationName(String organizationName);

    /**
     * Returns the legal form of this register of farmers.
     *
     * @return the legal form of this register of farmers
     */
    @AutoEscape
    public String getLegalForm();

    /**
     * Sets the legal form of this register of farmers.
     *
     * @param legalForm the legal form of this register of farmers
     */
    public void setLegalForm(String legalForm);

    /**
     * Returns the inn of this register of farmers.
     *
     * @return the inn of this register of farmers
     */
    @AutoEscape
    public String getInn();

    /**
     * Sets the inn of this register of farmers.
     *
     * @param inn the inn of this register of farmers
     */
    public void setInn(String inn);

    /**
     * Returns the kpp of this register of farmers.
     *
     * @return the kpp of this register of farmers
     */
    @AutoEscape
    public String getKpp();

    /**
     * Sets the kpp of this register of farmers.
     *
     * @param kpp the kpp of this register of farmers
     */
    public void setKpp(String kpp);

    /**
     * Returns the ogrn of this register of farmers.
     *
     * @return the ogrn of this register of farmers
     */
    @AutoEscape
    public String getOgrn();

    /**
     * Sets the ogrn of this register of farmers.
     *
     * @param ogrn the ogrn of this register of farmers
     */
    public void setOgrn(String ogrn);

    /**
     * Returns the registration area of this register of farmers.
     *
     * @return the registration area of this register of farmers
     */
    @AutoEscape
    public String getRegistrationArea();

    /**
     * Sets the registration area of this register of farmers.
     *
     * @param registrationArea the registration area of this register of farmers
     */
    public void setRegistrationArea(String registrationArea);

    /**
     * Returns the crop areas of this register of farmers.
     *
     * @return the crop areas of this register of farmers
     */
    @AutoEscape
    public String getCropAreas();

    /**
     * Sets the crop areas of this register of farmers.
     *
     * @param cropAreas the crop areas of this register of farmers
     */
    public void setCropAreas(String cropAreas);

    /**
     * Returns the date of registration of this register of farmers.
     *
     * @return the date of registration of this register of farmers
     */
    public Date getDateOfRegistration();

    /**
     * Sets the date of registration of this register of farmers.
     *
     * @param dateOfRegistration the date of registration of this register of farmers
     */
    public void setDateOfRegistration(Date dateOfRegistration);

    /**
     * Returns the is archived of this register of farmers.
     *
     * @return the is archived of this register of farmers
     */
    public boolean getIsArchived();

    /**
     * Returns <code>true</code> if this register of farmers is is archived.
     *
     * @return <code>true</code> if this register of farmers is is archived; <code>false</code> otherwise
     */
    public boolean isIsArchived();

    /**
     * Sets whether this register of farmers is is archived.
     *
     * @param isArchived the is archived of this register of farmers
     */
    public void setIsArchived(boolean isArchived);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.test.model.RegisterOfFarmers registerOfFarmers);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.test.model.RegisterOfFarmers> toCacheModel();

    @Override
    public com.test.model.RegisterOfFarmers toEscapedModel();

    @Override
    public com.test.model.RegisterOfFarmers toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
