package com.test.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.test.model.RegisterOfFarmers;

import com.test.service.RegisterOfFarmersLocalServiceUtil;

/**
 * The extended model base implementation for the RegisterOfFarmers service. Represents a row in the &quot;Test_RegisterOfFarmers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegisterOfFarmersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegisterOfFarmersImpl
 * @see com.test.model.RegisterOfFarmers
 * @generated
 */
public abstract class RegisterOfFarmersBaseImpl
    extends RegisterOfFarmersModelImpl implements RegisterOfFarmers {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a register of farmers model instance should use the {@link RegisterOfFarmers} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RegisterOfFarmersLocalServiceUtil.addRegisterOfFarmers(this);
        } else {
            RegisterOfFarmersLocalServiceUtil.updateRegisterOfFarmers(this);
        }
    }
}
