package com.test.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.test.model.RegisterOfDistricts;

import com.test.service.RegisterOfDistrictsLocalServiceUtil;

/**
 * The extended model base implementation for the RegisterOfDistricts service. Represents a row in the &quot;Test_RegisterOfDistricts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegisterOfDistrictsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegisterOfDistrictsImpl
 * @see com.test.model.RegisterOfDistricts
 * @generated
 */
public abstract class RegisterOfDistrictsBaseImpl
    extends RegisterOfDistrictsModelImpl implements RegisterOfDistricts {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a register of districts model instance should use the {@link RegisterOfDistricts} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RegisterOfDistrictsLocalServiceUtil.addRegisterOfDistricts(this);
        } else {
            RegisterOfDistrictsLocalServiceUtil.updateRegisterOfDistricts(this);
        }
    }
}
